import os

from dotenv import load_dotenv

load_dotenv()

HOST_AGENT_CONFIG = os.getenv('HOST_AGENT_CONFIG')

DEEP_SEEK_HOST = os.getenv('HOST_DEEP_SEEK')

AGENT_RECOMMEND_PRODUCTS_ID = os.getenv('AGENT_RECOMMEND_PRODUCTS_ID')
AGENT_RECOMMEND_SIMILAR_PRODUCTS_ID = os.getenv('AGENT_RECOMMEND_SIMILAR_PRODUCTS_ID')
RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY')

RAPIDAPI_HOST = os.getenv('RAPIDAPI_HOST')

S3_UPLOAD_API = os.getenv('S3_UPLOAD_API')

AGENT_IMAGE_VARIATIONS = "agent_image_variations"

AUTH_SERVICE_URL: str = os.getenv('AUTH_SERVICE_URL')

STABILITY_API_KEY: str = os.getenv('STABILITY_API_KEY')
STABILITY_API_URL: str = os.getenv('STABILITY_API_URL')
GOOGLE_VISION_API_KEY: str = os.getenv('GOOGLE_VISION_API_KEY')

API_KEY: str = os.getenv('API_KEY')
